---
- name: Install java and scala
  apt:
    name:
      - openjdk-8-jdk
      - openjdk-8-jre
      - scala
    state: present
  become: true

- name: Create sbt.list
  copy:
    dest: /etc/apt/sources.list.d/sbt.list
    content: deb https://repo.scala-sbt.org/scalasbt/debian all main
  become: true

- name: Create sbt_old.list
  copy:
    dest: /etc/apt/sources.list.d/sbt.list
    content: deb https://repo.scala-sbt.org/scalasbt/debian /
  become: true

- name: Import sbt gpg key
  shell: |
    curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" \
      | gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/scalasbt-release.gpg --import
  become: true

- name: Update permissions of file
  file:
    path: /etc/apt/trusted.gpg.d/scalasbt-release.gpg
    mode: 0644
  become: true

- name: Update all packages
  apt:
    name: "*"
    state: latest
    update_cache: true
  become: true

- name: Install sbt
  apt:
    name: sbt
    state: present
  become: true
