---
- name: Install java
  yum:
    name:
      - java-1.8.0-openjdk
      - java-1.8.0-openjdk-devel
    state: present
  become: true

- name: Remove bintray-rpm.repo
  file:
    path: /etc/yum.repos.d/bintray-rpm.repo
    state: absent
  become: true

- name: Download sbt-rpm.repo
  get_url:
    url: https://www.scala-sbt.org/sbt-rpm.repo
    dest: /etc/yum.repos.d/sbt-rpm.repo
  become: true

- name: Install sbt
  yum:
    name: sbt
    state: present
  become: true
