---
- name: Import microsoft keys
  shell: rpm --import https://packages.microsoft.com/keys/microsoft.asc
  become: true

- name: Get VSCode repo
  shell: sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
  become: true

- name: Install VSCode
  yum:
    name: code
    state: present
  become: true
